server:
  port: 8081

spring:
  application:
    name: trypto-collector
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    publisher-confirm-type: correlated
    publisher-returns: true

exchange:
  upbit:
    rest-url: https://api.upbit.com/v1/market/all
    ticker-url: https://api.upbit.com/v1/ticker
    ws-url: wss://api.upbit.com/websocket/v1
  bithumb:
    rest-url: https://api.bithumb.com/v1/market/all?isDetails=false
    ticker-url: https://api.bithumb.com/v1/ticker
    ws-url: wss://ws-api.bithumb.com/websocket/v1
  binance:
    rest-url: https://api.binance.com/api/v3/ticker/24hr
    ws-url: wss://stream.binance.com:9443/ws/!miniTicker@arr

ticker:
  redis-key-prefix: ticker

market-meta:
  redis-key-prefix: market-meta

influxdb:
  url: ${INFLUXDB_URL:http://localhost:8086}
  token: ${INFLUXDB_TOKEN:trypto-collector-token}
  org: ${INFLUXDB_ORG:trypto}
  bucket: ${INFLUXDB_BUCKET:candle}

logging:
  level:
    ksh.tryptocollector: DEBUG
    ksh.tryptocollector.exchange: INFO
