global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'trypto-collector'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['collector:9090']

  - job_name: 'trypto-backend'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['backend:8080']

  - job_name: 'trypto-engine'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['engine:8082']

  - job_name: 'mysqld'
    static_configs:
      - targets: ['mysqld-exporter:9104']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
